makehome: adding the update configuration function

diff --git a/bin/makehome b/bin/makehome
--- a/bin/makehome
+++ b/bin/makehome
@@ -2,7 +2,7 @@
 
 # This file is part of Danil Kutkevich <danil@kutkevich.org> home.
 
-USAGE="usage: ${CMD:=${0##*/}} [--apt] [--brew] [--update]"
+USAGE="usage: ${CMD:=${0##*/}} [--apt] [--brew] [--update] [--etc] [--root] [--home]"
 
 # APT (deb/dpkg/apt-get/aptitude)
 # <https://en.wikipedia.org/wiki/APT_(software)>.
@@ -30,7 +30,7 @@ FLAT_ADD_CLI="flatpak install --verbose flathub"
 RUST_ADD_CLI="cargo install"
 RUST_UPD_CLI="cargo install --force"
 
-OPT_ALL=0
+OPT_ALL=-1
 OPT_JOBS=`grep -c ^processor /proc/cpuinfo` OPT_JOBS=${OPT_JOBS:-1}
 
 # Options functions.
@@ -49,6 +49,9 @@ while [ "$1" != "$EOL" ]; do
         --appimage     ) OPT_APPI=0; OPT_ALL=-1;;
         --flatpak      ) OPT_FLAT=0; OPT_ALL=-1;;
         --rust         ) OPT_RUST=0; OPT_ALL=-1;;
+        --home         ) optcheck "$1" "$opt"; OPT_HOME="$1"; OPT_ALL=-1;;
+        --etc          ) OPT_ETCE=0; OPT_ALL=-1;;
+        --root         ) OPT_ROOT=0; OPT_ALL=-1;;
         --jobs         ) optcheck "$1" "$opt"; OPT_JOBS="$1"; shift;;
         --update       ) OPT_UPDATE=0;;
         -v | --verbose ) OPT_VERBOSE=0;;
@@ -140,7 +143,6 @@ BREW_ADD="$BREW_ADD zstd" # a-la gz/xz compression, required by gcc, curl, git, 
 APTO_ADD="$APTO_ADD zstd" # a-la gz/xz compression
 
 # Network.
-APPI_ADD="$APPI_ADD zsync2" # partial re-downloader a-la rsync/wget/curl <https://github.com/appimagecommunity/zsync2>
 BREW_ADD="$BREW_ADD aria2" # `aria2c https://your.tld/path/to/your.file` download client a-la curl/wget
 BREW_ADD="$BREW_ADD awscli" # `aws --version` # s3 command line client # default amazon aws ec2 client <https://github.com/aws/aws-cli>.
 BREW_ADD="$BREW_ADD axel" # download client a-la curl/wget
@@ -510,8 +512,6 @@ APPI_ADD="$APPI_ADD mattermost-desktop"
 # APTO_ADD="$APTO_ADD uswsusp" # FIXME: missing? # systemctl hibernate
 # APTO_ADD="$APTO_ADD xcalib" # returns: "Error - unsupported ramp size 0" (load icc/icm display color profiles (only calibration curves) <https://wiki.archlinux.org/index.php/ICC_Profiles#xcalib>)
 # APTO_ADD="$APTO_ADD xclip" # tmux and xorg clipboard integration <https://github.com/tmux-plugins/tmux-yank#linux-requirements>
-# APTO_ADD="$APTO_ADD xscreensaver-data-extra"
-# APTO_ADD="$APTO_ADD xscreensaver-gl-extra"
 # APTO_REM="$APTO_REM xserver-xorg-video-intel" # instead of intel using modesetting <https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1867668>
 # BREW_ADD="$BREW_ADD duplicity" # APTO_ADD="$APTO_ADD duplicity" # backuping
 APPI_ADD="$APPI_ADD flameshot" # FLAT_ADD="$FLAT_ADD org.flameshot.Flameshot" # screen shot util <https://github.com/flameshot-org/flameshot>
@@ -532,6 +532,8 @@ APTO_ADD="$APTO_ADD sassc libglib2.0-dev-bin" # dependencies of whitesur gtk the
 APTO_ADD="$APTO_ADD transmission" # torrent client # APTO_REM="$APTO_REM transmission-gtk"
 APTO_ADD="$APTO_ADD ubuntu-restricted-extras" # playing video in browser instead of download <https://askubuntu.com/questions/1122579/firefox-downloads-the-video-instead-of-playing-it#1122668>, <https://askubuntu.com/questions/56446/how-do-i-install-the-ubuntu-restricted-extras-package#56448>
 APTO_ADD="$APTO_ADD usb-creator-gtk" # create bootable/live usb/iso a-la popsicle
+APTO_ADD="$APTO_ADD xscreensaver-data-extra"
+APTO_ADD="$APTO_ADD xscreensaver-gl-extra"
 APTO_ADD="$APTO_ADD xserver-xorg-video-intel" # instead of modesetting using intel <https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1867668>
 APTO_REM="$APTO_REM gnome-mahjongg" # classic eastern tile game for gnome
 APTO_REM="$APTO_REM remmina" # gtk+ remote desktop client
@@ -570,6 +572,8 @@ APTO_ADD="$APTO_ADD libxml2-dev"
 # APTO_ADD="$APTO_ADD redis" APTO_DIS="$APTO_DIS redis-server" # felix
 # APTO_ADD="$APTO_ADD vpnc" # cisco vpn client
 
+OPT_DRY=0
+
 if [ "$OPT_VERBOSE" = 0 ] ; then
     RUST_UPD_CLI="$RUST_UPD_CLI --verbose"
     RUST_ADD_CLI="$RUST_ADD_CLI --verbose"
@@ -578,6 +582,7 @@ fi
 # APT/deb/dpkg/apt-get/aptitude
 # <https://en.wikipedia.org/wiki/APT_(software)>.
 if [ "$OPT_DPKG" = 0 ] || [ "$OPT_ALL" = 0 ]; then
+    OPT_DRY=-1
     sudo cat /dev/null || exit 1
     printf "Installing dpkg packages...\n\n"
     sh -c "sudo $APTO_REM_CLI $APTO_REM" || exit 1
@@ -588,6 +593,7 @@ fi
 # Homebrew
 # <https://brew.sh>.
 if [ "$OPT_BREW" = 0 ] || [ "$OPT_ALL" = 0 ]; then
+    OPT_DRY=-1
     printf "Installing homebrew packages...\n\n"
     # for src in ${BREW_REM_SRC}; do sh -c "$BREW_REM_SRC_CLI $src" || exit 1; done
     for src in ${BREW_ADD_SRC}; do sh -c "$BREW_ADD_SRC_CLI $src" || exit 1; done
@@ -598,6 +604,7 @@ fi
 # AppImage
 # <https://github.com/appimage/appimagekit>.
 if [ "$OPT_APPI" = 0 ] || [ "$OPT_ALL" = 0 ]; then
+    OPT_DRY=-1
     printf "Installing AppImage packages...\n\n"
     [ -n "$APPI_ADD" ] && [ "$APPI_ADD" != " " ] && sh -c "$APPI_ADD_CLI $APPI_ADD"
     printf "\n"
@@ -606,6 +613,7 @@ fi
 # Flatpak
 # <https://github.com/flatpak/flatpak>.
 if [ "$OPT_FLAT" = 0 ] || [ "$OPT_ALL" = 0 ]; then
+    OPT_DRY=-1
     printf "Installing Flatpak packages...\n\n"
     [ -n "$FLAT_ADD" ] && [ "$FLAT_ADD" != " " ] && sh -c "$FLAT_ADD_CLI $FLAT_ADD" || exit 1
     printf "\n"
@@ -615,6 +623,7 @@ fi
 # <https://github.com/rust-lang/cargo>,
 # <https://doc.rust-lang.org/cargo>.
 if [ "$OPT_RUST" = 0 ] || [ "$OPT_ALL" = 0 ]; then
+    OPT_DRY=-1
     if [ "$OPT_UPDATE" = 0 ]; then
         printf "Updating Rust Cargo packages...\n\n"
         for pkg in ${RUST_ADD}; do sh -c "$RUST_UPD_CLI $pkg" || exit 1; done
@@ -623,4 +632,83 @@ if [ "$OPT_RUST" = 0 ] || [ "$OPT_ALL" = 0 ]; then
         for pkg in ${RUST_ADD}; do sh -c "$RUST_ADD_CLI $pkg" || exit 1; done
     fi
     printf "\n"
+fi
+
+optcfg () {
+    local dir="$1"
+    git -C "$dir" rev-parse || exit 1
+    if [ $(sudo git -C "$dir" status --porcelain | wc -l) = 0 ]; then
+        printf "Already configured %s directory.\n" "$dir"
+    else
+        local IFS=$"
+"
+        for line in $(sudo git -C "$dir" status --porcelain); do
+            local mode=$(printf "%s" "$line" | awk '{print $1}')
+            local file=$(printf "%s" "$line" | awk '{print $2}')
+            local desc=""
+            for str in $(sudo git -C "$dir" status "$file" | grep "$file"); do
+                if [ "$desc" != "" ]; then
+                    desc="${desc} "
+                fi
+                desc="$desc"$(printf "%s" "$str" | awk '{print $1}' | sed 's/:$//')
+            done
+            if [ "$mode" = 'D' ]; then
+                str=$(printf "Restore %s %s %s file?" "$mode" "$desc" "$file")
+                while true; do
+                    read -p "$str " yn
+                    case $yn in
+                        [Yy]* ) sudo git -C "$dir" checkout "$file"; break;;
+                        [Nn]* ) break;;
+                        * ) echo "Please answer yes or no.";;
+                    esac
+                done
+            elif [ "$mode" = 'M' ]; then
+                str=$(printf "Restore %s %s %s file?" "$mode" "$desc" "$file")
+                sudo git -C "$dir" diff "$file"
+                while true; do
+                    read -p "$str " yn
+                    case $yn in
+                        [Yy]* ) sudo git -C "$dir" checkout "$file"; break;;
+                        [Nn]* ) break;;
+                        * ) echo "Please answer yes or no.";;
+                    esac
+                done
+            else
+                printf "Invalid %s state (%s) of %s file.\n" "$mode" "$desc" "$file"
+            fi
+        done
+    fi
+}
+
+# $HOME user home directory
+# <https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure>.
+if [ -n "$OPT_HOME" ] && [ "$OPT_HOME" != " " ]; then
+    OPT_DRY=-1
+    sudo cat /dev/null || exit 1
+    printf "Configuring %s directory...\n\n" "$OPT_HOME"
+    optcfg "$OPT_HOME"
+fi
+
+# /etc of host-specific system-wide configuration
+# <https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure>.
+if [ "$OPT_ETCE" = 0 ] || [ "$OPT_ALL" = 0 ]; then
+    OPT_DRY=-1
+    sudo cat /dev/null || exit 1
+    printf "Configuring /etc directory...\n\n"
+    optcfg "/etc"
+fi
+
+# / root directory of host-specific system-wide configuration
+# <https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard#Directory_structure>.
+if [ "$OPT_ROOT" = 0 ] || [ "$OPT_ALL" = 0 ]; then
+    OPT_DRY=-1
+    sudo cat /dev/null || exit 1
+    printf "Configuring / root directory...\n\n"
+    optcfg "/"
+fi
+
+# Dry run.
+if [ "$OPT_DRY" = 0 ]; then
+    printf "$USAGE\n"
+    exit 1
 fi
