pacman packages: feat: dependencies clean (wip)

diff --git a/bin/pacman-packages b/bin/pacman-packages
--- a/bin/pacman-packages
+++ b/bin/pacman-packages
@@ -1,32 +1,57 @@
 #!/bin/bash
-# user=danil
-install_command="pacman --sync --needed --verbose"
-# install_aur_command="yay --aur --sync --noprovides --noconfirm --verbose"
+
+export install=${install:--1}
+export depclean=${depclean:--1}
+
+while [ $# -gt 0 ]; do
+    case "$1" in
+        --install)
+            let install=1
+            ;;
+        --depclean)
+            let depclean=1
+            ;;
+        *)
+            printf "***************************\n"
+            printf "* Error: Invalid argument.*\n"
+            printf "***************************\n"
+            exit 1
+    esac
+    shift
+done
 
 # Common packages.
-install="$install community/emacs-nox"
-install="$install core/mlocate"
-install="$install core/sudo"
-install="$install extra/git"
-install="$install extra/htop"
-install="$install extra/vim"
+packages="$packages emacs-nox" # community/emacs-nox
+packages="$packages git" # extra/git
+packages="$packages htop" # extra/htop
+packages="$packages mlocate" # core/mlocate
+packages="$packages sudo" # core/sudo
+packages="$packages vim" # extra/vim
 
 # Arch.
-install="$install base-devel" # package group required to build PKGBUILD package from aur (arch user repository)
-install="$install extra/namcap" # analysis utility that checks binary packages and source PKGBUILDs for common mistakes <https://wiki.archlinux.org/index.php/Namcap>
+packages="$packages base-devel" # package group required to build PKGBUILD package from aur (arch user repository)
+packages="$packages namcap" # extra/namcap: analysis utility that checks binary packages and source PKGBUILDs for common mistakes <https://wiki.archlinux.org/index.php/Namcap>
 
 # Server.
-install="$install extra/ntp"
+packages="$packages ntp" # extra/ntp
 
 # Golang.
-install="$install community/go"
+packages="$packages go" # community/go
 
 # Kubernetes/k8s.
-install="$install community/docker"
-install="$install community/kubectl"
-# install_aur="$install_aur aur/kubeadm-bin"
-# install_aur="$install_aur aur/kubelet-bin"
+packages="$packages docker" # community/docker
+packages="$packages kubectl" # community/kubectl
+# packages_aur="$packages_aur kubeadm-bin" # aur/kubeadm-bin
+# packages_aur="$packages_aur kubelet-bin" # aur/kubelet-bin
 
-$install_command $install || exit 1
-# echo $user
-# su $user --shell=/bin/bash --command "$install_aur_command $install_aur" || exit 1
+packages=$(echo $packages | tr " " "\n" | sort | tr "\n" " ")
+
+count=0
+[[ $depclean -eq 1 ]] && count=$((count+1)) && pacman --remove --recursive --unneeded --verbose $(comm -23 <(pacman --query --quiet | sort) <(echo "$packages yay" | tr " " "\n" | sort))
+[[ $install -eq 1 ]] && count=$((count+1)) && pacman --sync --needed --verbose $packages
+
+# install_aur_command="yay --aur --sync --noprovides --noconfirm --verbose"
+
+if [[ ${count} -lt 1 ]]; then
+    printf "usage: pacman-packages [--install] [--depclean]\n"
+fi
